from __future__ import annotations

"""tests/test_quickstart.py — HH1.2: end-to-end coverage for `tes quickstart`
/ `tracegauge quickstart`. Runs the real scoring pipeline against the bundled
sample transcript (tes/data/quickstart_sample_session.jsonl) -- deliberately
not stubbed, since the entire point of this command is that it works out of
the box against what actually ships in the wheel, with no local judge probe
and no network call.
"""

import pytest
import tes.cli as cli


def test_quickstart_exits_zero_and_prints_a_real_report(monkeypatch, capsys):
    monkeypatch.setattr("sys.argv", ["tes", "quickstart"])
    with pytest.raises(SystemExit) as exc:
        cli.main()
    assert exc.value.code == 0

    out = capsys.readouterr().out
    assert "TOKEN-EFFICIENCY SCORER" in out
    assert "quickstart_sample_session" in out
    assert "COST ANNOTATION" in out
    assert "This ran entirely from what shipped in the installed package" in out


def test_quickstart_never_probes_a_local_judge(monkeypatch, capsys):
    # The whole point of `quickstart` is zero network/local-model dependency
    # -- assert the judge-availability probe is never even called, not just
    # that its result doesn't appear in the output.
    called = []
    monkeypatch.setattr(cli, "is_judge_available", lambda *a, **k: called.append(1) or False)
    monkeypatch.setattr("sys.argv", ["tes", "quickstart"])
    with pytest.raises(SystemExit):
        cli.main()
    assert called == []

    out = capsys.readouterr().out
    assert "TRAJECTORY QUALITY" in out
    assert "UNAVAILABLE (no local judge configured)" in out


def test_quickstart_bundled_fixture_is_reachable_via_importlib_resources():
    from importlib import resources

    sample_path = resources.files("tes.data") / "quickstart_sample_session.jsonl"
    with resources.as_file(sample_path) as concrete_path:
        assert concrete_path.exists()
        content = concrete_path.read_text(encoding="utf-8")
        assert content.strip()
        # 146 lines, generated by scripts/gen_quickstart_sample.py. Sized to clear the
        # research-recon turn gate of the shipped baseline (tes/data/cc_baselines.json
        # scope_gates, 143 turns) so the demo prints a real TOKEN ECONOMY verdict.
        assert len(content.strip().splitlines()) == 146


def test_quickstart_shows_a_verdict_a_waste_finding_with_proof_and_the_breakdown(
    monkeypatch, capsys
):
    # Regression for the rebuilt baseline raising the research-recon gate above the old 50-turn
    # sample: quickstart printed UNAVAILABLE / 0 waste events and no test noticed.
    monkeypatch.setattr("sys.argv", ["tes", "quickstart"])
    with pytest.raises(SystemExit) as exc:
        cli.main()
    assert exc.value.code == 0
    out = capsys.readouterr().out
    token_section = out.split("TRAJECTORY QUALITY")[0]
    assert "Verdict:     UNAVAILABLE" not in token_section
    assert "Session scope too small" not in token_section
    assert any(v in token_section for v in ("within_band", "above_p75", "below_p25"))
    assert "Events:  0 detected" not in out
    assert "REPEATED-FAILED-RETRY" in out
    assert "turns:" in out  # proof turns are attached to the event
    # The finding is the waste event with its proof turns (above). "Context dominates" is not a
    # lever any more: the cost is shown as an informational breakdown, with no LEVER section.
    assert "── COST BREAKDOWN " in out
    assert "Context re-send (cache reads)" in out and "Detected waste" in out
    assert "Total (priced)" in out
    assert "── LEVER ──" not in out
    assert "checkpointing" not in out


def test_quickstart_sample_is_labelled_synthetic():
    from importlib import resources

    text = (resources.files("tes.data") / "quickstart_sample_session.jsonl").read_text(
        encoding="utf-8"
    )
    assert text.splitlines()[0].count("Synthetic demo session") == 1
