from __future__ import annotations

"""tes/classify.py — Task-type classifier for CC session records.

Self-contained implementation (no scripts/ import) so the installed wheel
works without repo access.

Public API:
    classify_session(record: dict) -> str
"""

# ---------------------------------------------------------------------------
# Session-level overrides (misclassification corrections)
# ---------------------------------------------------------------------------

SESSION_OVERRIDES: dict[str, str] = {
    # d57f0f0e: STATUS CHECK session, "eval" fired from "v2 eval artifact" in description
    "d57f0f0e-56aa-4d3a-9637-98719c8dfe47": "research-recon",
}

# ---------------------------------------------------------------------------
# Task taxonomy
# ---------------------------------------------------------------------------

TASK_TYPES: list[str] = [
    "ml-eval",
    "debug-fix",
    "infra-deploy",
    "research-recon",
    "feature-build",
]

# Keywords are matched case-insensitively as substrings.
# Priority order: ml-eval > debug-fix > infra-deploy > research-recon > feature-build
KEYWORDS: dict[str, set[str]] = {
    "ml-eval": {
        "experiment",
        "training",
        "eval",
        "metric",
        "accuracy",
        "loss",
        "benchmark",
        "epoch",
        "dataset",
        "mlflow",
        "wandb",
        "hyperparameter",
        "finetune",
        "fine-tune",
        # Specific to ML model families in this corpus
        "diffusion",
        "optuna",
    },
    "debug-fix": {
        "bug",
        "fix",
        "error",
        "exception",
        "traceback",
        "broken",
        "failing",
        "crash",
        "debug",
        "investigate",
        "wrong",
        "incorrect",
        "test fail",
        "regression",
        "issue",
        "problem",
    },
    "infra-deploy": {
        "deploy",
        "dockerfile",
        "ci/cd",
        "github action",
        "cloud run",
        "gcp",
        "vm",
        "startup",
        "provision",
        "env",
        "environment",
        "kubernetes",
        "docker",
        "terraform",
        "pipeline",
        "workflow",
        "secret",
        "credential",
        "permission",
    },
    "research-recon": {
        "audit",
        "survey",
        "inventory",
        "report",
        "analyze",
        "analysis",
        "document",
        "recon",
        "review",
        "investigate",
        "scan",
        "summarize",
        "summary",
        "status",
    },
}

# ---------------------------------------------------------------------------
# Boilerplate markers for <local-command-caveat> sessions
# ---------------------------------------------------------------------------

CAVEAT_PREFIX = (
    "<local-command-caveat>"
    "Caveat: The messages below were generated by the user while running local commands."
)

BOILERPLATE_PREFIXES: tuple[str, ...] = (
    "<local-command-caveat>",
    "<command-name>",
    "<command-message>",
    "<local-command-stdout>",
    "<local-command-stderr>",
)


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------


def _is_boilerplate_snippet(snippet: str) -> bool:
    """Return True if a turn's content_snippet is local-command boilerplate."""
    for prefix in BOILERPLATE_PREFIXES:
        if snippet.startswith(prefix):
            return True
    return False


def _effective_task_description(record: dict) -> tuple[str, int | None]:
    """Return (effective_task_description, override_turn_index | None).

    For normal sessions the task_description field is used directly and
    override_turn_index is None.

    For <local-command-caveat> sessions the first non-boilerplate user turn
    with non-empty content_snippet is used; its turn_index is returned so
    callers can report which turn was chosen.
    """
    digest: dict = record.get("digest", {})
    task_desc: str = digest.get("task_description", "")

    if not task_desc.startswith(CAVEAT_PREFIX):
        return task_desc, None

    # Walk turns to find first real user message
    turns: list[dict] = digest.get("turns", [])
    for turn in turns:
        if turn.get("role") != "user":
            continue
        snippet: str = turn.get("content_snippet", "")
        if snippet and not _is_boilerplate_snippet(snippet):
            return snippet, turn.get("turn_index")

    # Fallback: caveat session with no usable turn — return empty string
    return "", None


def _match_type(text: str) -> str:
    """Apply keyword matching in priority order; return task type string."""
    lower = text.lower()
    priority_order = ["ml-eval", "debug-fix", "infra-deploy", "research-recon"]
    for task_type in priority_order:
        for keyword in KEYWORDS[task_type]:
            if keyword in lower:
                return task_type
    return "feature-build"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def classify_session(record: dict) -> str:
    """Classify a single pool_adapted record and return its task type.

    Checks SESSION_OVERRIDES first; falls back to keyword matching.

    Parameters
    ----------
    record:
        A dict parsed from one line of pool_adapted.jsonl or a CC session
        record produced by tes.adapt.adapt_session.

    Returns
    -------
    str
        One of: 'feature-build', 'ml-eval', 'debug-fix', 'infra-deploy',
        'research-recon'.
    """
    sid = record.get("session_id", "")
    if sid in SESSION_OVERRIDES:
        return SESSION_OVERRIDES[sid]
    effective_text, _ = _effective_task_description(record)
    return _match_type(effective_text)


__all__ = ["classify_session", "TASK_TYPES", "KEYWORDS", "SESSION_OVERRIDES"]
