from __future__ import annotations

"""Task-type classifier for token-efficiency-scorer pool sessions.

Classifies each CC session into one of five task types using
rule/keyword matching on the task description (or the first
non-boilerplate user turn for <local-command-caveat> sessions).

Usage:
    python scripts/task_classifier.py --selftest
    python scripts/task_classifier.py --session-id <session_id>
"""

import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
POOL_ADAPTED_PATH = REPO_ROOT / "data" / "corpus_pool" / "pool_adapted.jsonl"
JUDGE_SCORES_PATH = REPO_ROOT / "data" / "pool_judge_scores.jsonl"

# ---------------------------------------------------------------------------
# Session-level overrides (misclassification corrections)
# ---------------------------------------------------------------------------

SESSION_OVERRIDES: dict[str, str] = {
    # d57f0f0e: STATUS CHECK session, "eval" fired from "v2 eval artifact" in description
    "d57f0f0e-56aa-4d3a-9637-98719c8dfe47": "research-recon",
}

# ---------------------------------------------------------------------------
# Task taxonomy
# ---------------------------------------------------------------------------

TASK_TYPES: list[str] = [
    "ml-eval",
    "debug-fix",
    "infra-deploy",
    "research-recon",
    "feature-build",
]

# Keywords are matched case-insensitively as substrings.
# Priority order: ml-eval > debug-fix > infra-deploy > research-recon > feature-build
KEYWORDS: dict[str, set[str]] = {
    "ml-eval": {
        "experiment",
        "training",
        "eval",
        "metric",
        "accuracy",
        "loss",
        "benchmark",
        "epoch",
        "dataset",
        "mlflow",
        "wandb",
        "hyperparameter",
        "finetune",
        "fine-tune",
        # Specific to ML model families in this corpus
        "diffusion",
        "optuna",
    },
    "debug-fix": {
        "bug",
        "fix",
        "error",
        "exception",
        "traceback",
        "broken",
        "failing",
        "crash",
        "debug",
        "investigate",
        "wrong",
        "incorrect",
        "test fail",
        "regression",
        "issue",
        "problem",
    },
    "infra-deploy": {
        "deploy",
        "dockerfile",
        "ci/cd",
        "github action",
        "cloud run",
        "gcp",
        "vm",
        "startup",
        "provision",
        "env",
        "environment",
        "kubernetes",
        "docker",
        "terraform",
        "pipeline",
        "workflow",
        "secret",
        "credential",
        "permission",
    },
    "research-recon": {
        "audit",
        "survey",
        "inventory",
        "report",
        "analyze",
        "analysis",
        "document",
        "recon",
        "review",
        "investigate",
        "scan",
        "summarize",
        "summary",
        "status",
    },
}

# ---------------------------------------------------------------------------
# Boilerplate markers for <local-command-caveat> sessions
# ---------------------------------------------------------------------------

CAVEAT_PREFIX = (
    "<local-command-caveat>"
    "Caveat: The messages below were generated by the user while running local commands."
)

BOILERPLATE_PREFIXES: tuple[str, ...] = (
    "<local-command-caveat>",
    "<command-name>",
    "<command-message>",
    "<local-command-stdout>",
    "<local-command-stderr>",
)


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------


def _is_boilerplate_snippet(snippet: str) -> bool:
    """Return True if a turn's content_snippet is local-command boilerplate."""
    for prefix in BOILERPLATE_PREFIXES:
        if snippet.startswith(prefix):
            return True
    return False


def _effective_task_description(record: dict) -> tuple[str, int | None]:
    """Return (effective_task_description, override_turn_index | None).

    For normal sessions the task_description field is used directly and
    override_turn_index is None.

    For <local-command-caveat> sessions the first non-boilerplate user turn
    with non-empty content_snippet is used; its turn_index is returned so
    callers can report which turn was chosen.
    """
    digest: dict = record.get("digest", {})
    task_desc: str = digest.get("task_description", "")

    if not task_desc.startswith(CAVEAT_PREFIX):
        return task_desc, None

    # Walk turns to find first real user message
    turns: list[dict] = digest.get("turns", [])
    for turn in turns:
        if turn.get("role") != "user":
            continue
        snippet: str = turn.get("content_snippet", "")
        if snippet and not _is_boilerplate_snippet(snippet):
            return snippet, turn.get("turn_index")

    # Fallback: caveat session with no usable turn — return empty string
    return "", None


def _match_type(text: str) -> str:
    """Apply keyword matching in priority order; return task type string."""
    lower = text.lower()
    priority_order = ["ml-eval", "debug-fix", "infra-deploy", "research-recon"]
    for task_type in priority_order:
        for keyword in KEYWORDS[task_type]:
            if keyword in lower:
                return task_type
    return "feature-build"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def classify_session(record: dict) -> str:
    """Classify a single pool_adapted record and return its task type.

    Checks SESSION_OVERRIDES first; falls back to keyword matching.

    Parameters
    ----------
    record:
        A dict parsed from one line of pool_adapted.jsonl.

    Returns
    -------
    str
        One of: 'feature-build', 'ml-eval', 'debug-fix', 'infra-deploy',
        'research-recon'.
    """
    sid = record.get("session_id", "")
    if sid in SESSION_OVERRIDES:
        return SESSION_OVERRIDES[sid]
    effective_text, _ = _effective_task_description(record)
    return _match_type(effective_text)


# ---------------------------------------------------------------------------
# Data loading helpers
# ---------------------------------------------------------------------------


def _load_pool() -> list[dict]:
    """Load all records from pool_adapted.jsonl."""
    records: list[dict] = []
    with POOL_ADAPTED_PATH.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def _load_judge_scores() -> dict[str, dict]:
    """Load judge scores keyed by session_id."""
    scores: dict[str, dict] = {}
    with JUDGE_SCORES_PATH.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                entry = json.loads(line)
                scores[entry["session_id"]] = entry
    return scores


# ---------------------------------------------------------------------------
# Selftest
# ---------------------------------------------------------------------------


def run_selftest() -> None:
    """Run the full selftest and print results to stdout."""
    pool = _load_pool()
    judge_scores = _load_judge_scores()

    scored_ids: set[str] = set(judge_scores.keys())
    strict_gate_ids: set[str] = {
        sid for sid, entry in judge_scores.items() if entry.get("verdict") == "MUCH_BETTER"
    }

    # --- Classify all sessions and record caveat info ---
    classifications: dict[str, str] = {}
    caveat_info: list[tuple[str, int, str]] = []  # (session_id, turn_index, snippet)

    for record in pool:
        sid: str = record["session_id"]
        task_desc: str = record.get("digest", {}).get("task_description", "")
        effective_text, override_turn = _effective_task_description(record)

        if task_desc.startswith(CAVEAT_PREFIX):
            snippet_80 = effective_text[:80]
            turn_idx = override_turn if override_turn is not None else -1
            caveat_info.append((sid, turn_idx, snippet_80))

        classifications[sid] = classify_session(record)

    # --- Build per-type counts ---
    def _counts(session_subset: set[str] | None = None) -> dict[str, int]:
        """Count classifications for sessions in subset (None = all pool)."""
        c: dict[str, int] = {t: 0 for t in TASK_TYPES}
        for record in pool:
            sid = record["session_id"]
            if session_subset is not None and sid not in session_subset:
                continue
            c[classifications[sid]] += 1
        return c

    all_pool_ids = {r["session_id"] for r in pool}
    counts_all = _counts(None)
    counts_scored = _counts(scored_ids & all_pool_ids)
    counts_strict = _counts(strict_gate_ids & all_pool_ids)

    # --- Consistency check: re-classify 3 times ---
    consistent = True
    for record in pool:
        sid = record["session_id"]
        first = classifications[sid]
        for _ in range(2):  # already classified once; do 2 more
            if classify_session(record) != first:
                consistent = False
                break
        if not consistent:
            break

    # ----------------------------------------------------------------
    # Output
    # ----------------------------------------------------------------
    print("=== TASK CLASSIFIER SELFTEST ===")
    print()

    print(f"Command-caveat sessions ({len(caveat_info)} found):")
    for sid, turn_idx, snippet in caveat_info:
        print(f"  {sid[:8]}: using turn {turn_idx}, snippet: {snippet!r}")
    print()

    col_w = 16
    print("Per-type distribution:")
    header = f"  {'Type':<{col_w}} {'Pool(181)':>10}  {'Scored(143)':>12}  {'Strict-gate(77)':>15}"
    print(header)
    for task_type in TASK_TYPES:
        print(
            f"  {task_type:<{col_w}} {counts_all[task_type]:>10}"
            f"  {counts_scored[task_type]:>12}"
            f"  {counts_strict[task_type]:>15}"
        )
    total_all = sum(counts_all.values())
    total_scored = sum(counts_scored.values())
    total_strict = sum(counts_strict.values())
    print(f"  {'TOTAL':<{col_w}} {total_all:>10}  {total_scored:>12}  {total_strict:>15}")
    print()

    # Strict-gate coverage
    min_n = 10
    clearing: list[str] = []
    below: list[str] = []
    for task_type in TASK_TYPES:
        n = counts_strict[task_type]
        if n >= min_n:
            clearing.append(task_type)
        else:
            below.append(f"{task_type}({n})")
    print("Strict-gate coverage:")
    print(f"  Types clearing min-N>={min_n}: {clearing}")
    print(f"  Types below min-N:        {below}")
    print()

    consistency_label = "PASS (deterministic, no LLM)" if consistent else "FAIL"
    print(f"Consistency check: {consistency_label}")
    print()
    print("=== DONE ===")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    args = sys.argv[1:]

    if "--selftest" in args:
        run_selftest()
        return

    if "--session-id" in args:
        idx = args.index("--session-id")
        if idx + 1 >= len(args):
            print("Error: --session-id requires a session ID argument", file=sys.stderr)
            sys.exit(1)
        target_id = args[idx + 1]
        pool = _load_pool()
        for record in pool:
            if record["session_id"] == target_id:
                task_type = classify_session(record)
                effective_text, override_turn = _effective_task_description(record)
                print(f"session_id:    {record['session_id']}")
                print(f"task_type:     {task_type}")
                if override_turn is not None:
                    print(f"caveat_turn:   {override_turn}")
                print(f"task_snippet:  {effective_text[:120]!r}")
                return
        print(f"Error: session_id {target_id!r} not found in pool", file=sys.stderr)
        sys.exit(1)
        return

    print("Usage:")
    print("  python scripts/task_classifier.py --selftest")
    print("  python scripts/task_classifier.py --session-id <session_id>")
    sys.exit(0)


if __name__ == "__main__":
    main()
